travis:
  secure:
    BINSTAR_TOKEN: EhREfhy2P/9x0Vu9cgUCeES2hfZmnicQspjW+1nC8HY6JhssRMmiD7O8Lw0wGiGMV/qIc3wYlFG33IOIcg46yVf4QQ6JJ6KD8TVLDtG6Xt0O0ij93aHzQigNQlGc0ceXFSBU29JAGyCnB2KOY8PJ6OEoG3dM1iT0rTqi8cRDgmPudvN5qPF1ZP+VqvTzDv+bFnFE5wPurpGJeO6e7e+/uA4jnSTFbDnWdc9jrHoSwRHpByzGj2DpILZrIfYY53Wx/KEgWfknfaraxzuWn4xn2Ag5l0n29EfSCClKELeQiux6r1F7KawBbVrKOLMx56VeOGsUwHzTZiYfJi5ZjcbjkJT9pv8eSzqe9QIJqnVdx7X2VbW6CsG9vHy3o/LcRT2rgJlhVqb5aGF1PeGOpUy+MWzDI4W0ZkbXuht+mtQXbFaKA2NdU2Ont80bpGoPjQkpzlRKQvJmPh6YJTnMu7rhHmEcY6i8ff4Lyps00xIGFXJzHPka4BA8fNY6wQ8qOIK90zSNx0XroHO9CdgxdjU5QN9tDY1u0nG/4aGgwjtWjVVykjDIuzOVfxfIsjTKlpyUF+zEBs2e3dE1aT3b1mh2vKom8+B6Rbk+qJ9+lAQgBpyHOB5O5sib9fYOaOh/eeb4OpccDmDXJiipNU27s76msAA5QVq1VmhD9OZnUM8P7V8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
