travis:
  secure:
    BINSTAR_TOKEN: qcC+laQzE/4NzjEldpxDheRC5wMkNBDZ0Mpt/uRGiqTuaY4PhlohiSCchPNwD+nDgPkGPCHBsyg16ad4ILGQ6wFUlTAfqFgLqjabZBnRQG6GkwzM86XzOvFOkbXCJxiksv36Bnd+Z+foDy4TDamzW1mZTv4fjEMzdAEeypxylvqTH4PWAf/62BgEmSbMkHWxhvIFKmP4epAKrsiqoUfDzLXlZU57bFqnV2GCCACIqOclBPCr2+LAXJ9tfj6L0Wihujusw0gt3qQN2In/k8Za4aRU94WOYgwju5DJLYuxgPRSOJ5TxGX8GlVP3cUfPy1da0L9z180k/hGyjPb+gKIB0+QOCDRFU/pQbNCTuBTIp6wO5nzRIbVKXt09GMgoBD+5QFnCFN6RzLT/JOvZR+6MM5b6gcpceBYrGlGr9aIAF18KlgGennt0eVheiI5Tur09+u7ZFEFu4m/v2x1x1UunQG/7/1BxEaUQjztx2M/QwNCL9HQXLlqB5kiO6IM8DQxLwUwVlt9EiLKlUcm2WQPKgavS3K88GOI2GaqJwI5VF6r4RKF2sqv73CIk4tMNOpEA13ZeHBAV/uQ0LPTQvVmVDTJBluWIr/6T6VIdkkjhfa9E91vO4m2QAFFWFfH7oJlbwp7aU2uLUPzRIOpeW9BTRUcM8Ipadpx7RLLkVrRs6g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
