travis:
  secure:
    BINSTAR_TOKEN: EIMnr1lfTVpGmFdv3XPqr28wUs3saxxam/HnJ3xGfUib7uDYAKtB/ubG4ddNbs33fDc9DjsVmirNNWS1JGc9/ubneaxvEYiC0kdTIXckarJRv9isp0G8tnRsbZFS3OJaOfgzztlLk0aKdL5d0YRwPwyDj8fKE+NMcW7D5BMf+dWO6gEHJSZ4TByG0x1aDUYjqEUAiG59eE8adWYCMwjgbKDQ29sggCp3LRr1BRYFXwkEuMR+BfUBVfz/WUHYuW2AjXDS8Tvz55af3FXCnHx3MCJq6NGsogfmM6kQDIYGfvnTiRiP5pRIAU6KmufWuysvaBpKn2r4oPnp7UrijBOwSW3Ts+eQgSlovzWmYia8enjsyC+o1WCi1N1boJNgyeJ4pcsr1G+riHRx8zVJEnr0JHVikxr08xXuynP0UOEYFyB7fp3bnzTRS+H0I1PF2eA05bwwMyu56xXXB9uoqaC/Q+8bhLDZuyP9lgzVNRmLQpIz+QhlqdcdteDsLH/A/oKPwqJa6HCLQAjfHHYDA+gSBs1FGEoD08YlJjffOjIFu2GugdjSPFrelvuTtqEeWzYdtvaKRJpWpn9mFTOziUNqYLRBH3WvLe1Sndf26X4IAHdct6DWwLfkiUq6kgqOQzL7YhXaNJcF5fefpQqhaIZiZIbyMzBv/22UouwgdJ2pEhk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
